### PR TITLE
Adjusting positioning and sizing of notification bar

### PR DESCRIPTION
**Pull request by rhamilto**
@spadgett, @sg00dwin

screen shot 2017-08-29 at 11 04 28 am

Note:  in order to fit the notification drawer icon and the system status icon, I had to reduce the max width of the branding image from 230px to 196px.  OCP will need to be updated per https://gist.github.com/rhamilto/c5c671d4dba9da2b8b62ff3fe0ad9f41.  I opened https://github.com/openshift/online/pull/1408 to resolve the issue in Online.

IMPORTANT:  the following screenshots were taken with Chrome's "Toggle device toolbar" enabled, thus eliminating the scrollbar.  If you resize your browser window to 320px, the utility nav will wrap to the second line because the toolbar is present, thus consuming 15 additional pixels of horizontal space, which doesn't occur in a true mobile device since the scrollbar is painted above the UI.

localhost-9000-dev-console-project-my-project-overview 1
localhost-9000-dev-console-project-my-project-overview
localhost-9000-dev-console-project-my-project-overview iphone 5

TODO:

- [ ] Consume pending upstream changes to make expanded drawer layout better at mobile.
localhost-9000-dev-console-project-my-project-browse-deployments iphone 5 1

### CODE REVIEW

**Comment by spadgett** [comment]
@rhamilto I'm not sure if we should just truncate the name :( We might need alternative icons for origin and online as well if necessary. Or maybe scale it smaller?

**Comment by rhamilto** [comment]
> @rhamilto I'm not sure if we should just truncate the name :( We might need alternative icons for origin and online as well if necessary. Or maybe scale it smaller?

ok.  seems like we should do what we do for OCP and stack vertically.  vertical

@sg00dwin, any chance you've got the source file (where fonts aren't converted to outlines) for the stacked SVG?

**Comment by sg00dwin** [comment]
@rhamilto I do not have a source file for just text.
Looking on the brand product logo page I see Logotype_RH_OpenShiftContainerPlatform_wLogo_RGB_White.svg
(github doesn't support attaching .svg)

**Comment by rhamilto** [comment]
Updated to use a stacked logo.  Thoughts @spadgett, @sg00dwin?

**Comment by rhamilto** [comment]
In turns out we can squeeze "OPENSHIFT ORIGIN" and "OPENSHIFT ONLINE" in if we reduce the width of the image as well as the right padding on the system status icon.  We'll still need changes for OCP and Online, but I've documented those at https://gist.github.com/rhamilto/c5c671d4dba9da2b8b62ff3fe0ad9f41

@spadgett, I think this is ready for merge.

**Comment by spadgett** [comment]
Thanks @rhamilto

**Pull request merged**
